services:
  app:
    build: .
    init: true
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - TZ=Asia/Tokyo
      - DATABASE_PATH=/data/data.db
    volumes:
      - dbdata:/data
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  dbdata:
