services:
  app:
    build: .
    init: true
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - TZ=Asia/Tokyo
      - DATABASE_PATH=/data/data.db
    volumes:
      - dbdata:/data
    restart: unless-stopped

volumes:
  dbdata:
